# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Terminal 1
    before: echo 'before script'
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Terminal 2
    init: npm install
    command: npm  run dev
  - name: Terminal 3
    init: echo 'This is Terminal 3'
    Command: echo 'Hello from terminal 3'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
